"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
#Brute-forcing
fibonacci = [1, 1]
upperBound = int(input("Upper bound? "))
while fibonacci[-1] < upperBound:
    fibonacci.append(fibonacci[-1] + fibonacci[-2])
print(sum([i if i % 2 == 0 else 0 for i in fibonacci]))    
    